# Generated by Django 3.0.8 on 2020-07-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200709_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='created_by',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='created_by',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
