# Generated by Django 3.0.8 on 2020-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200710_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='last_edited',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
