# Generated by Django 3.0.8 on 2020-07-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_map_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
