# Generated by Django 3.0.8 on 2020-07-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200716_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='state',
            field=models.CharField(choices=[('AR', 'archieved'), ('OP', 'on_progress'), ('NA', 'not_archieved')], default='NA', max_length=20),
        ),
    ]
