# Generated by Django 3.0.8 on 2020-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamestate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
