# Generated by Django 3.0.8 on 2020-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200719_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='map_file',
            new_name='map_file_id',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_image',
            new_name='map_image_id',
        ),
        migrations.AddField(
            model_name='map',
            name='map_file_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='map_image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
