# Generated by Django 3.0.8 on 2020-07-19 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_auto_20200719_2312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamestate',
            unique_together={('user', 'game_map')},
        ),
    ]
